baseURL: "https://avanish.is/"
title: Avanish Shrestha | My Personal Blog
paginate: 10
theme: PaperMod

enableRobotsTXT: false
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Avanish Shrestha
  description: "My Personal Blog"
  keywords: [avanish, blog]
  author: Avanish Shrestha
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: true
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Avanish Shrestha"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  # profileMode:
  #   enabled: false # needs to be explicitly set
  #   title: ExampleSite
  #   subtitle: "This is subtitle"
  #   imageUrl: "<img location>"
  #   imageWidth: 120
  #   imageHeight: 120
  #   imageTitle: my image
  #   buttons:
  #     - name: Posts
  #       url: posts
  #     - name: Tags
  #       url: tags

  # home-info mode
  homeInfoParams:
    enabled: true
    Title: "Hi! I am Avanish Shrestha! \U0001F44B"
    Content: I am the Managing Director of [Beam Lab Pvt. Ltd.](https://beamlab.co). We work on Computer Viion and Machine Learning projects in collaboration with [Baksters Co. Ltd.](https://baksters.com) and [Intelligent Systems Laboratory](http://isl.scitech.au.edu). We also maintain several machine learning based projects and packages for these organizations.

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/avanishshrestha"
    - name: github
      url: "https://github.com/avanish"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/avanish/avanish/blob/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  # fuseOpts:
  #   isCaseSensitive: false
  #   shouldSort: true
  #   location: 0
  #   distance: 1000
  #   threshold: 0.4
  #   minMatchCharLength: 0
  #   limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
  #   keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: beamlab
      name: beamlab.co
      url: https://beamlab.co
      weight: 1
    - identifier: twelveletter
      name: twelveletter.co
      url: https://twelveletter.co
      weight: 2
    - identifier: smartworks
      name: smartworkstechnology.co
      url: https://smartworkstechnology.co
      weight: 3
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true

markup:
  highlight:
    # noClasses: false
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai